os.environ.setdefault("IP", "0.0.0.0")
os.environ.setdefault("PORT", "5000")
os.environ.setdefault("SECRET_KEY", "a1b1K99J51Bc0A44O38Ib5Le3HI68")
os.environ.setdefault("MONGO_URI", "mongodb+srv://diyCookBook:cooking@diycookbook.zjmmc.mongodb.net/diyCookBook?retryWrites=true&w=majority")
os.environ.setdefault("MONGO_DBNAME", "diyCookBook")